#!/bin/sh

# assumes you have chrooted into /mnt and cloned repo to /home/mike/workspace

echo "Setting local time"
ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
echo "Generating /etc/adjtime"
hwclock --systohc

echo "Generating locales"
sed -i 's/#en_IE.UTF-8 UTF-8/en_IE.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "Creating locale.conf"
echo "LANG=en_IE.UTF-8" > /etc/locale.conf

echo "Persisting console keyboard layout"
echo "KEYMAP=uk" > /etc/vconsole.conf

echo "Setting hostname"
echo "thinkpad" > /etc/hostname
echo "Setting network config"
echo -e "127.0.0.1\t\tlocalhost\n::1\t\t\tlocalhost\n127.0.1.1\t\tthinkpad" > /etc/hosts

echo "Installing pacman packages"
pacman -S --noconfirm alsa-utils ardour base-devel cmus doas dosfstools efibootmgr feh git grub intel-ucode krita ksh man-db mpv mtools neomutt neovim networkmanager nitrogen openssh os-prober picom qutebrowser rtorrent tor xf86-video-intel xclip xdg-utils xorg xorg-xinit zathura zathura-pdf-mupdf zig zip

echo "Enabling NetworkManager"
systemctl enable NetworkManager

echo "Set root password"
passwd

"Creating mike user"
useradd -G wheel,audio,video,storage,ftp,http,rfkill,uucp -s /bin/ksh mike
"Set mike password"
passwd mike

"Mounting /dev/sda1 to /boot/efi"
mount --mkdir /dev/sda1 /boot/efi
"Installing grub"
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub_uefi --recheck
"Making grub config"
grub-mkconfig -o /boot/grub/grub.cfg

echo -e 'permit persist :wheel\n' > /etc/doas.conf
chmod -c 0400 /etc/doas.conf

echo "Linking bin and config directories"
# make symlinks for files and nested directories recursively
makeLinks () {
    local source=$1
    local target=$2
    local dirs=$3

    for dir in $dirs; do
        mkdir -p $target/$dir &&
        files=$(ls $source/$dir)
        for file in $files; do
            if [[ -d $source/$dir/$file ]]; then
                makeLinks $source/$dir $target/$dir $(ls $source/$dir)
            else
                ln $source/$dir/$file $target/$dir/$file
            fi
        done
    done        
}

$home=/home/mike
$path=$home/workspace/system

bin=$(ls -l $path | grep "^[d]" | awk '{print $9}' | grep -Ev '(config|rc|scripts)')
makeLinks $path $home/bin "${bin[@]}"

configs=$(ls -l $path/config | grep "^[d]" | awk '{print $9}')
makeLinks $path/config $home/.config "${configs[@]}"

ln $path/rc/.??* $home/
ln $path/config/fehbg $home/.fehbg
ln -s $path/scripts/* /usr/local/sbin

for dir in $(ls $home/bin); do
    echo -e "\nInstalling" $dir "\n"
    cd $dir
    make
    make install
    cd ..
done

echo "Making home directories"
mkdir $home/doc $home/img $home/music $home/ogrrs $home/video $home/vimwiki

echo "Setting default browser"
xdg-settings set default-web-browser qutebrowser.desktop
xdg-mime default qutebrowser.desktop x-scheme-handler/https x-scheme-handler/http
